const $ = id => document.getElementById(id);
const homeView = $('homeView');
const editorView = $('editorView');
const canvas = $('canvas');
const canvasWrap = $('canvasWrap');
const nodesLayer = $('nodesLayer');
const edgesGroup = $('edgesGroup');
const codeArea = $('mermaidCode');
const COLORS = ['#1687ff', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6', '#64748b'];
let state = { nodes: [], edges: [], title: 'Flowchart sin título', selected: null, selectedEdge: null, tool: 'select', zoom: 1, pan: { x: 0, y: 0 } };
let directoryHandle = null, currentFileHandle = null, drag = null, panDrag = null, connectionDrag = null, history = [], future = [], codeTimer;
let selectedIds = new Set(), marqueeDrag = null, spaceCreate = null, ghostConnection = null;

const sampleState = () => ({
  nodes: [
    { id: 'idea', label: 'Nueva idea', x: 220, y: 220, type: 'node', color: null, fontSize: 13, align: 'center' },
    { id: 'research', label: 'Investigar contexto', x: 500, y: 220, type: 'node', color: null, fontSize: 13, align: 'center' },
    { id: 'decision', label: '¿Está lista?', x: 790, y: 195, type: 'decision', color: null, fontSize: 13, align: 'center' },
    { id: 'share', label: 'Compartir resultado', x: 1080, y: 120, type: 'node', color: null, fontSize: 13, align: 'center' },
    { id: 'iterate', label: 'Iterar propuesta', x: 1080, y: 350, type: 'node', color: null, fontSize: 13, align: 'center' }
  ],
  edges: [
    { from: 'idea', to: 'research', label: '', shape: 'curve', direction: 'forward' },
    { from: 'research', to: 'decision', label: '', shape: 'curve', direction: 'forward' },
    { from: 'decision', to: 'share', label: 'Sí', shape: 'corner', direction: 'forward' },
    { from: 'decision', to: 'iterate', label: 'No', shape: 'corner', direction: 'forward' }
  ]
});

function showToast(message) { const el = $('toast'); el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2500); }
function safeId(text) { let id = text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '') || 'nodo'; const base = id; let n = 2; while (state.nodes.some(x => x.id === id)) id = base + n++; return id; }
function snapshot() { history.push(JSON.stringify({ nodes: state.nodes, edges: state.edges, title: state.title })); if (history.length > 60) history.shift(); future = []; }
function restore(raw) { selectedIds.clear(); const s = JSON.parse(raw); state.nodes = s.nodes; state.edges = s.edges; state.title = s.title; state.selected = null; state.selectedEdge = null; $('diagramTitle').value = s.title; renderAll(); }
function markChanged() { $('saveState').textContent = 'Cambios sin guardar'; updateCode(); }
function normalizeData(data) { return { nodes: (data.nodes || []).map(n => ({ color: null, ...n })), edges: (data.edges || []).map(e => ({ label: '', shape: 'curve', direction: 'forward', ...e })) }; }
function openEditor(data = sampleState(), title = 'Flowchart sin título') { selectedIds.clear(); state = { ...state, ...normalizeData(data), title, selected: null, selectedEdge: null, tool: 'select', zoom: 1, pan: { x: 0, y: 0 } }; history = []; future = []; $('diagramTitle').value = title; homeView.classList.add('hidden'); editorView.classList.remove('hidden'); renderAll(); fitView(); }
function renderAll() { renderNodes(); renderEdges(); updateCode(); renderMinimap(); updateToolbars(); }

function renderNodes() {
  nodesLayer.innerHTML = '';
  state.nodes.forEach(n => {
    const el = document.createElement('div');
    el.className = `diagram-node ${n.type === 'decision' ? 'decision' : ''} ${state.selected === n.id ? 'selected' : ''}`;
    el.dataset.id = n.id; el.style.left = n.x + 'px'; el.style.top = n.y + 'px'; el.style.setProperty('--node-color', n.color || '#1687ff');
    el.innerHTML = `<span class="node-kind">${n.type === 'decision' ? 'DECISIÓN' : ''}</span><span class="node-label"></span>${['top', 'right', 'bottom', 'left'].map(p => `<button class="port ${p}" data-side="${p}" aria-label="Conectar hacia ${p}"></button>`).join('')}<span class="ghost-node"></span>`;
    el.querySelector('.node-label').textContent = n.label;
    el.addEventListener('pointerdown', startNodeDrag); el.addEventListener('click', nodeClick); el.addEventListener('dblclick', e => { if (!e.target.classList.contains('port')) { e.stopPropagation(); beginInlineEdit(n.id); } });
    el.querySelectorAll('.port').forEach(port => { port.addEventListener('pointerdown', startConnection); port.addEventListener('mouseenter', showGhost); port.addEventListener('mouseleave', hideGhost); });
    nodesLayer.appendChild(el);
  });
}
function nodeClick(e) { if (e.target.classList.contains('port')) return; e.stopPropagation(); state.selected = e.currentTarget.dataset.id; state.selectedEdge = null; renderAll(); }
function beginInlineEdit(id) { const n = state.nodes.find(x => x.id === id), el = document.querySelector(`[data-id="${id}"] .node-label`); if (!n || !el) return; state.selected = id; el.contentEditable = 'true'; el.focus(); document.getSelection().selectAllChildren(el); const original = n.label; const finish = () => { el.contentEditable = 'false'; const value = el.textContent.trim(); if (value && value !== original) { snapshot(); n.label = value; markChanged(); } else el.textContent = original; renderAll(); }; el.onblur = finish; el.onkeydown = e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); el.blur(); } if (e.key === 'Escape') { el.textContent = original; el.blur(); } }; }
function startNodeDrag(e) { if (e.button !== 0 || e.target.classList.contains('port') || e.target.isContentEditable) return; e.stopPropagation(); const n = state.nodes.find(x => x.id === e.currentTarget.dataset.id); state.selected = n.id; state.selectedEdge = null; snapshot(); drag = { n, startX: e.clientX, startY: e.clientY, x: n.x, y: n.y, moved: false }; e.currentTarget.setPointerCapture(e.pointerId); e.currentTarget.onpointermove = moveNode; e.currentTarget.onpointerup = endNodeDrag; updateToolbars(); }
function moveNode(e) { if (!drag) return; drag.moved = true; drag.n.x = drag.x + (e.clientX - drag.startX) / state.zoom; drag.n.y = drag.y + (e.clientY - drag.startY) / state.zoom; const el = document.querySelector(`[data-id="${drag.n.id}"]`); el.style.left = drag.n.x + 'px'; el.style.top = drag.n.y + 'px'; renderEdges(); renderMinimap(); }
function endNodeDrag() { if (drag?.moved) markChanged(); drag = null; }

function nodeSize(n) { return n.type === 'decision' ? { w: 120, h: 120 } : { w: 180, h: 72 }; }
function anchor(n, side) { const { w, h } = nodeSize(n); return { top: { x: n.x + w / 2, y: n.y }, right: { x: n.x + w, y: n.y + h / 2 }, bottom: { x: n.x + w / 2, y: n.y + h }, left: { x: n.x, y: n.y + h / 2 } }[side || 'right']; }
function opposite(side) { return { top: 'bottom', right: 'left', bottom: 'top', left: 'right' }[side]; }
function showGhost(e) { if (connectionDrag) return; const node = state.nodes.find(n => n.id === e.currentTarget.closest('.diagram-node').dataset.id), side = e.currentTarget.dataset.side, ghost = e.currentTarget.closest('.diagram-node').querySelector('.ghost-node'), offsets = { top: [0, -145], right: [225, 0], bottom: [0, 145], left: [-225, 0] }; ghost.style.transform = `translate(${offsets[side][0]}px,${offsets[side][1]}px)`; ghost.classList.add('show'); }
function hideGhost(e) { e.currentTarget.closest('.diagram-node').querySelector('.ghost-node').classList.remove('show'); }
function startConnection(e) { e.preventDefault(); e.stopPropagation(); const port = e.currentTarget, nodeId = port.closest('.diagram-node').dataset.id, side = port.dataset.side, node = state.nodes.find(n => n.id === nodeId), start = anchor(node, side); connectionDrag = { nodeId, side, start, startX: e.clientX, startY: e.clientY, moved: false }; port.setPointerCapture(e.pointerId); port.onpointermove = moveConnection; port.onpointerup = endConnection; $('connectionPreview').classList.remove('hidden'); hideGhost(e); }
function moveConnection(e) { if (!connectionDrag) return; connectionDrag.moved = Math.hypot(e.clientX - connectionDrag.startX, e.clientY - connectionDrag.startY) > 6; const rect = canvas.getBoundingClientRect(), end = { x: (e.clientX - rect.left) / state.zoom, y: (e.clientY - rect.top) / state.zoom }; $('connectionPreview').setAttribute('d', curvePath(connectionDrag.start, end)); }
function endConnection(e) { if (!connectionDrag) return; const info = connectionDrag; connectionDrag = null; $('connectionPreview').classList.add('hidden'); const targetEl = document.elementFromPoint(e.clientX, e.clientY)?.closest('.diagram-node'); if (info.moved && targetEl && targetEl.dataset.id !== info.nodeId) createEdge(info.nodeId, targetEl.dataset.id, info.side); else if (!info.moved) createDirectionalNode(info.nodeId, info.side); }
function createDirectionalNode(fromId, side) { const from = state.nodes.find(n => n.id === fromId), offset = { top: [0, -190], right: [280, 0], bottom: [0, 190], left: [-280, 0] }[side]; snapshot(); const id = safeId('Nuevo proceso'), node = { id, label: 'Nuevo proceso', x: from.x + offset[0], y: from.y + offset[1], type: 'node', color: from.color || null }; state.nodes.push(node); state.edges.push({ from: fromId, to: id, fromSide: side, toSide: opposite(side), label: '', shape: 'curve', direction: 'forward' }); state.selected = id; renderAll(); markChanged(); setTimeout(() => beginInlineEdit(id), 50); }
function createEdge(from, to, side = 'right') { snapshot(); state.edges.push({ from, to, fromSide: side, toSide: opposite(side), label: '', shape: 'curve', direction: 'forward' }); state.selected = null; state.selectedEdge = state.edges.length - 1; renderAll(); markChanged(); }
function curvePath(a, b) { const dx = Math.max(55, Math.abs(b.x - a.x) * .45); return `M ${a.x} ${a.y} C ${a.x + (b.x >= a.x ? dx : -dx)} ${a.y}, ${b.x - (b.x >= a.x ? dx : -dx)} ${b.y}, ${b.x} ${b.y}`; }
function cornerPath(a, b) { const mid = a.x + (b.x - a.x) / 2; return `M ${a.x} ${a.y} L ${mid} ${a.y} L ${mid} ${b.y} L ${b.x} ${b.y}`; }


function updateToolbars() { const node = state.nodes.find(n => n.id === state.selected), edge = state.edges[state.selectedEdge]; $('selectionToolbar').classList.toggle('hidden', !node); $('edgeToolbar').classList.toggle('hidden', !edge); if (node) $('nodeColor').value = node.color || '#1687ff'; if (edge) { $('edgeShape').value = edge.shape || 'curve'; $('edgeLabel').value = edge.label || ''; $('edgeDirection').value = edge.direction || 'forward'; } }
function renderMinimap() { const svg = $('minimapSvg'); svg.innerHTML = ''; state.edges.forEach(e => { const a = state.nodes.find(n => n.id === e.from), b = state.nodes.find(n => n.id === e.to); if (!a || !b) return; const line = document.createElementNS('http://www.w3.org/2000/svg', 'line'); line.setAttribute('x1', (a.x + 80) / 7 + 10); line.setAttribute('y1', (a.y + 35) / 7 + 8); line.setAttribute('x2', (b.x + 80) / 7 + 10); line.setAttribute('y2', (b.y + 35) / 7 + 8); line.setAttribute('stroke', '#4b5668'); svg.appendChild(line); }); state.nodes.forEach(n => { const r = document.createElementNS('http://www.w3.org/2000/svg', 'rect'); r.setAttribute('x', n.x / 7 + 10); r.setAttribute('y', n.y / 7 + 8); r.setAttribute('width', 24); r.setAttribute('height', 9); r.setAttribute('rx', 2); r.setAttribute('fill', n.color || '#1687ff'); svg.appendChild(r); }); }

function mermaidArrow(edge) { if (edge.shape === 'dashed') return edge.direction === 'both' ? '<-.->' : edge.direction === 'back' ? '<-.-' : '-.->'; return edge.direction === 'both' ? '<-->' : edge.direction === 'back' ? '<--' : '-->'; }
function generateCode() { let out = 'flowchart TD\n'; state.nodes.forEach(n => { const label = n.label.replace(/"/g, "'"); out += n.type === 'decision' ? `  ${n.id}{"${label}"}\n` : `  ${n.id}["${label}"]\n`; }); state.edges.forEach((e, i) => { out += `  ${e.from} ${mermaidArrow(e)}${e.label ? `|${e.label}|` : ''} ${e.to}\n`; out += `  %% flowchart-edge:${i} shape=${e.shape || 'curve'} fromSide=${e.fromSide || 'right'} toSide=${e.toSide || 'left'}\n`; }); state.nodes.forEach(n => out += `  style ${n.id} fill:${n.color || '#1687ff'},stroke:${n.color || '#1687ff'},color:#ffffff\n`); return out.trim(); }
function updateCode() { const code = generateCode(); if (document.activeElement !== codeArea) codeArea.value = code; $('codeStats').textContent = `${state.nodes.length} nodos · ${state.edges.length} conexiones`; }
function logicalLayout(nodes, edges) { const ids = new Set(nodes.map(n => n.id)), incoming = new Map(nodes.map(n => [n.id, 0])), outgoing = new Map(nodes.map(n => [n.id, []])); edges.forEach(e => { if (ids.has(e.from) && ids.has(e.to)) { incoming.set(e.to, incoming.get(e.to) + 1); outgoing.get(e.from).push(e.to); } }); const roots = nodes.filter(n => !incoming.get(n.id)).map(n => n.id), queue = (roots.length ? roots : [nodes[0]?.id]).filter(Boolean).map(id => [id, 0]), levels = new Map(); while (queue.length) { const [id, level] = queue.shift(); if ((levels.get(id) ?? -1) >= level) continue; levels.set(id, level); outgoing.get(id)?.forEach(next => queue.push([next, level + 1])); } nodes.forEach(n => { if (!levels.has(n.id)) levels.set(n.id, Math.max(0, ...levels.values()) + 1); }); const groups = {}; nodes.forEach(n => (groups[levels.get(n.id)] ||= []).push(n)); Object.entries(groups).forEach(([level, group]) => group.forEach((n, row) => { n.x = 220 + Number(level) * 300; n.y = 160 + row * 180; })); }
function parseCode(code) {
  const nodeMap = new Map(), edges = [], colors = new Map(), metadata = [], old = new Map(state.nodes.map(n => [n.id, n]));
  const ensureNode = (id, label = id, type = 'node') => { if (!nodeMap.has(id)) { const prior = old.get(id); nodeMap.set(id, { id, label, type, color: prior?.color || null, x: prior?.x || 0, y: prior?.y || 0 }); } else if (label !== id) { const n = nodeMap.get(id); n.label = label; n.type = type; } };
  code.split('\n').forEach(line => {
    let m = line.match(/^\s*style\s+([\w-]+)\s+fill:(#[0-9a-fA-F]{3,8})/); if (m) { colors.set(m[1], m[2]); return; }
    m = line.match(/^\s*%%\s*flowcharts?-edge:(\d+)\s+shape=(\w+)(?:\s+dashed=(true|false))?\s+fromSide=(\w+)\s+toSide=(\w+)(?:\s+labelPos=(\d+))?/); if (m) { metadata[+m[1]] = { shape: m[2], dashed: m[3] === 'true', fromSide: m[4], toSide: m[5], labelPos: Number(m[6] || 50) }; return; }
    const definitions = [...line.matchAll(/([\w-]+)\s*(\[|\{)["']?(.*?)["']?(\]|\})/g)];
    definitions.forEach(d => ensureNode(d[1], d[3].replace(/["']$/, ''), d[2] === '{' ? 'decision' : 'node'));
    const clean = line.replace(/([\w-]+)\s*(?:\[|\{)["']?.*?["']?(?:\]|\})/g, '$1');
    m = clean.match(/^\s*([\w-]+)\s*(<-->|<--|-->|<-\.->|<-\.-|-\.->)\s*(?:\|([^|]+)\|\s*)?([\w-]+)/);
    if (m) { ensureNode(m[1]); ensureNode(m[4]); edges.push({ from: m[1], to: m[4], label: m[3] || '', shape: m[2].includes('.') ? 'dashed' : 'curve', direction: m[2].startsWith('<') && m[2].endsWith('>') ? 'both' : m[2].startsWith('<') ? 'back' : 'forward' }); }
  });
  const nodes = [...nodeMap.values()]; if (!nodes.length) return;
  nodes.forEach(n => { if (colors.has(n.id)) n.color = colors.get(n.id); }); edges.forEach((e, i) => Object.assign(e, { fromSide: 'right', toSide: 'left' }, metadata[i] || {}));
  logicalLayout(nodes, edges); snapshot(); selectedIds.clear(); state.nodes = nodes; state.edges = edges; renderAll(); markChanged(); fitView();
}
codeArea.addEventListener('input', () => { clearTimeout(codeTimer); codeTimer = setTimeout(() => parseCode(codeArea.value), 600); });
function addNode(type, x = 450, y = 300) { snapshot(); const label = type === 'decision' ? 'Nueva decisión' : 'Nuevo proceso', id = safeId(label); state.nodes.push({ id, label, x, y, type, color: null }); state.selected = id; state.selectedEdge = null; renderAll(); markChanged(); setTimeout(() => beginInlineEdit(id), 50); }
function deleteSelected() { if (!state.selected) return; snapshot(); state.nodes = state.nodes.filter(n => n.id !== state.selected); state.edges = state.edges.filter(e => e.from !== state.selected && e.to !== state.selected); state.selected = null; renderAll(); markChanged(); }
function duplicateSelected() { const n = state.nodes.find(x => x.id === state.selected); if (!n) return; snapshot(); const copy = { ...n, id: safeId(n.label), x: n.x + 36, y: n.y + 36, label: n.label + ' copia' }; state.nodes.push(copy); state.selected = copy.id; renderAll(); markChanged(); }
function applyTransform() { canvas.style.transform = `translate(${state.pan.x}px,${state.pan.y}px) scale(${state.zoom})`; $('zoomLabel').textContent = Math.round(state.zoom * 100) + '%'; }
function fitView() { if (!state.nodes.length) return; const minX = Math.min(...state.nodes.map(n => n.x)), maxX = Math.max(...state.nodes.map(n => n.x + 180)), minY = Math.min(...state.nodes.map(n => n.y)), maxY = Math.max(...state.nodes.map(n => n.y + 120)); state.zoom = Math.max(.35, Math.min(.95, (canvasWrap.clientWidth - 200) / (maxX - minX || 1), (canvasWrap.clientHeight - 150) / (maxY - minY || 1))); state.pan = { x: (canvasWrap.clientWidth - (maxX - minX) * state.zoom) / 2 - minX * state.zoom, y: (canvasWrap.clientHeight - (maxY - minY) * state.zoom) / 2 - minY * state.zoom }; applyTransform(); }
const recentDB = () => new Promise((resolve, reject) => { const req = indexedDB.open('Flowcharts', 1); req.onupgradeneeded = () => req.result.createObjectStore('recent', { keyPath: 'id' }); req.onsuccess = () => resolve(req.result); req.onerror = () => reject(req.error); });
async function recentStore(mode = 'readonly') { const db = await recentDB(); return db.transaction('recent', mode).objectStore('recent'); }
async function getRecents() { const store = await recentStore(); return new Promise((resolve, reject) => { const r = store.getAll(); r.onsuccess = () => resolve(r.result.sort((a, b) => b.updated - a.updated)); r.onerror = () => reject(r.error); }); }
async function addRecent(handle, name) { if (!handle) return; const store = await recentStore('readwrite'), item = { id: `${handle.name}:${Date.now()}`, name: name || handle.name, handle, updated: Date.now() }; await new Promise((resolve, reject) => { const r = store.put(item); r.onsuccess = resolve; r.onerror = () => reject(r.error); }); renderRecent(); }
async function removeRecent(id) { const store = await recentStore('readwrite'); await new Promise(resolve => { const r = store.delete(id); r.onsuccess = resolve; }); renderRecent(); }
async function renderRecent() { if (!window.indexedDB) return; let items = []; try { items = await getRecents(); } catch { return; } const grid = $('fileGrid'); grid.innerHTML = ''; $('recentSection').classList.toggle('hidden', !items.length); items.forEach(item => { const card = document.createElement('article'); card.className = 'file-card'; card.tabIndex = 0; card.innerHTML = '<span class="file-card-icon">⌁</span><strong></strong><small>Archivo guardado localmente</small><div class="file-card-actions"><span>Abrir archivo</span><button class="remove-recent">×</button></div>'; card.querySelector('strong').textContent = item.name; card.querySelector('.remove-recent').onclick = e => { e.stopPropagation(); removeRecent(item.id); }; card.onclick = async () => { try { const permission = await item.handle.queryPermission({ mode: 'readwrite' }); if (permission !== 'granted' && await item.handle.requestPermission({ mode: 'readwrite' }) !== 'granted') throw Error(); const file = await item.handle.getFile(); currentFileHandle = item.handle; openFromText(await file.text(), file.name.replace(/\.(text|txt)$/i, '')); } catch { card.querySelector('small').textContent = 'No se encontró el archivo'; card.querySelector('small').classList.add('recent-error'); } }; grid.appendChild(card); }); }
async function chooseFolder() { if (!window.showDirectoryPicker) return showToast('Tu navegador no permite elegir carpetas'); try { directoryHandle = await window.showDirectoryPicker({ mode: 'readwrite' }); for await (const [name, handle] of directoryHandle.entries()) if (handle.kind === 'file' && /\.(text|txt)$/i.test(name)) await addRecent(handle, name); } catch (e) { if (e.name !== 'AbortError') showToast('No fue posible abrir la carpeta'); } }
function openFromText(text, title) { try { const parsed = JSON.parse(text); if (parsed.nodes) openEditor(parsed, parsed.title || title); else throw Error(); } catch { state.nodes = []; state.edges = []; parseCode(text); state.title = title; $('diagramTitle').value = title; homeView.classList.add('hidden'); editorView.classList.remove('hidden'); } }
async function openFile() { if (!window.showOpenFilePicker) return $('fileInput').click(); try { const [handle] = await window.showOpenFilePicker({ types: [{ description: 'Flowchart', accept: { 'text/plain': ['.txt', '.text'] } }] }); const file = await handle.getFile(); currentFileHandle = handle; await addRecent(handle, file.name); openFromText(await file.text(), file.name.replace(/\.(text|txt)$/i, '')); } catch (e) { if (e.name !== 'AbortError') showToast('No se pudo abrir el archivo'); } }
async function saveDiagram() { state.title = $('diagramTitle').value.trim() || 'Flowchart sin título'; const content = JSON.stringify({ version: 3, title: state.title, nodes: state.nodes, edges: state.edges, groups: state.groups || [], mermaid: generateCode() }, null, 2); try { if (!currentFileHandle) currentFileHandle = await window.showSaveFilePicker({ suggestedName: state.title + '.text', types: [{ description: 'Flowchart', accept: { 'text/plain': ['.text'] } }] }); const w = await currentFileHandle.createWritable(); await w.write(content); await w.close(); await addRecent(currentFileHandle, currentFileHandle.name); markSaved(); showToast('Flowchart guardado'); } catch (e) { if (e.name !== 'AbortError') showToast('No se pudo guardar'); } }
async function copyCode() { try { await navigator.clipboard.writeText(generateCode()); showToast('Código Mermaid copiado'); } catch { showToast('No se pudo copiar'); } }
async function saveExport() { try { const folder = await window.showDirectoryPicker({ mode: 'readwrite' }), name = ($('diagramTitle').value.trim() || 'flowchart') + '.txt', handle = await folder.getFileHandle(name, { create: true }), w = await handle.createWritable(); await w.write(generateCode()); await w.close(); await addRecent(handle, name); showToast('Código guardado como .txt'); } catch (e) { if (e.name !== 'AbortError') showToast('No se pudo guardar'); } }
function showExport() { $('exportCode').textContent = generateCode(); $('exportStats').textContent = `${state.nodes.length} NODOS · ${state.edges.length} CONEXIONES`; $('exportDialog').showModal(); }

$('newDiagramBtn').onclick = () => { currentFileHandle = null; openEditor(sampleState()); }; $('openFolderBtn').onclick = chooseFolder; $('openFileBtn').onclick = openFile; $('fileInput').onchange = async e => { const f = e.target.files[0]; if (f) openFromText(await f.text(), f.name.replace(/\.(text|txt)$/i, '')); }; $('clearRecentBtn').onclick = async () => { const store = await recentStore('readwrite'); await new Promise(resolve => { const r = store.clear(); r.onsuccess = resolve; }); renderRecent(); };
$('backBtn').onclick = () => { editorView.classList.add('hidden'); homeView.classList.remove('hidden'); renderRecent(); }; document.querySelectorAll('.tool[data-tool]').forEach(b => b.onclick = () => { if (b.dataset.tool === 'node' || b.dataset.tool === 'decision') addNode(b.dataset.tool === 'decision' ? 'decision' : 'node'); });
canvas.addEventListener('dblclick', e => { if (e.target === canvas || e.target === nodesLayer) { const r = canvas.getBoundingClientRect(); addNode('node', (e.clientX - r.left) / state.zoom, (e.clientY - r.top) / state.zoom); } }); canvas.addEventListener('click', e => { if (e.target === canvas || e.target === nodesLayer) { state.selected = null; state.selectedEdge = null; renderAll(); } });
canvasWrap.addEventListener('contextmenu', e => e.preventDefault()); canvasWrap.addEventListener('pointerdown', e => { if (e.button !== 2) return; panDrag = { x: e.clientX, y: e.clientY, panX: state.pan.x, panY: state.pan.y }; canvasWrap.setPointerCapture(e.pointerId); }); canvasWrap.addEventListener('pointermove', e => { if (!panDrag) return; state.pan.x = panDrag.panX + e.clientX - panDrag.x; state.pan.y = panDrag.panY + e.clientY - panDrag.y; applyTransform(); }); canvasWrap.addEventListener('pointerup', e => { if (e.button === 2) panDrag = null; }); canvasWrap.addEventListener('wheel', e => { e.preventDefault(); const r = canvasWrap.getBoundingClientRect(), mx = e.clientX - r.left, my = e.clientY - r.top, old = state.zoom, next = Math.max(.3, Math.min(1.8, old * (e.deltaY < 0 ? 1.1 : .9))); state.pan.x = mx - (mx - state.pan.x) * next / old; state.pan.y = my - (my - state.pan.y) * next / old; state.zoom = next; applyTransform(); }, { passive: false });
$('editNodeBtn').onclick = () => beginInlineEdit(state.selected); $('duplicateNodeBtn').onclick = duplicateSelected; $('deleteNodeBtn').onclick = deleteSelected; $('nodeColor').oninput = e => { const n = state.nodes.find(n => n.id === state.selected); if (n) { n.color = e.target.value; renderAll(); markChanged(); } }; $('edgeShape').onchange = updateSelectedEdge; $('edgeDirection').onchange = updateSelectedEdge; $('edgeLabel').oninput = updateSelectedEdge; $('deleteEdgeBtn').onclick = () => { if (state.selectedEdge == null) return; snapshot(); state.edges.splice(state.selectedEdge, 1); state.selectedEdge = null; renderAll(); markChanged(); };
function updateSelectedEdge() { const e = state.edges[state.selectedEdge]; if (!e) return; e.shape = $('edgeShape').value; e.direction = $('edgeDirection').value; e.label = $('edgeLabel').value; renderEdges(); updateCode(); markChanged(); }
$('saveBtn').onclick = saveDiagram; $('exportBtn').onclick = showExport; $('copyCodeBtn').onclick = copyCode; $('copyExportBtn').onclick = copyCode; $('saveExportBtn').onclick = saveExport; $('closeExportBtn').onclick = $('closeExportBtn2').onclick = () => $('exportDialog').close(); $('diagramTitle').oninput = () => { state.title = $('diagramTitle').value; markChanged(); }; $('fitBtn').onclick = fitView; $('zoomInBtn').onclick = () => { state.zoom = Math.min(1.8, state.zoom + .1); applyTransform(); }; $('zoomOutBtn').onclick = () => { state.zoom = Math.max(.3, state.zoom - .1); applyTransform(); }; $('collapseCodeBtn').onclick = () => document.querySelector('.code-panel').classList.toggle('collapsed'); $('undoBtn').onclick = () => { if (history.length) { future.push(JSON.stringify({ nodes: state.nodes, edges: state.edges, title: state.title })); restore(history.pop()); } }; $('redoBtn').onclick = () => { if (future.length) { history.push(JSON.stringify({ nodes: state.nodes, edges: state.edges, title: state.title })); restore(future.pop()); } };
document.addEventListener('keydown', e => { if (e.key === 'Delete' && !document.activeElement.isContentEditable && !['INPUT', 'TEXTAREA', 'SELECT'].includes(document.activeElement.tagName)) state.selectedEdge != null ? $('deleteEdgeBtn').click() : deleteSelected(); if ((e.ctrlKey || e.metaKey) && e.key === 's') { e.preventDefault(); saveDiagram(); } }); renderRecent();

// Enhanced Flowcharts interactions
function selectedNodes() { return state.nodes.filter(n => selectedIds.has(n.id)); }
function selectOnly(id) { selectedIds = new Set(id ? [id] : []); state.selected = id || null; state.selectedEdge = null; }
function nodeVisualType(n) { return n.shape || n.type || 'node'; }
function nodeSize(n) { return nodeVisualType(n) === 'decision' ? { w: 120, h: 120 } : { w: 180, h: 72 }; }
function renderNodes() {
  nodesLayer.innerHTML = '';
  state.nodes.forEach(n => {
    const type = nodeVisualType(n), el = document.createElement('div');
    el.className = `diagram-node ${type === 'decision' ? 'decision' : ''} ${type === 'rounded' ? 'rounded' : ''} ${selectedIds.has(n.id) ? 'selected' : ''} ${n.color ? 'colored' : ''}`;
    el.dataset.id = n.id; el.style.left = n.x + 'px'; el.style.top = n.y + 'px'; el.style.setProperty('--node-color', n.color || '#1687ff'); el.style.setProperty('--node-font-size', (n.fontSize || 13) + 'px'); el.style.setProperty('--node-align', n.align || 'center');
    el.innerHTML = `<span class="node-kind">${type === 'decision' ? 'DECISIÓN' : ''}</span><span class="node-label"></span>${['top','right','bottom','left'].map(p => `<button class="port ${p}" data-side="${p}" aria-label="Conectar hacia ${p}"></button>`).join('')}<span class="ghost-node"></span>`;
    el.querySelector('.node-label').textContent = n.label;
    el.addEventListener('pointerdown', startNodeDrag); el.addEventListener('click', nodeClick); el.addEventListener('dblclick', e => { if (!e.target.classList.contains('port')) { e.stopPropagation(); beginInlineEdit(n.id); } });
    el.querySelectorAll('.port').forEach(port => { port.addEventListener('pointerdown', startConnection); port.addEventListener('mouseenter', showGhost); port.addEventListener('mouseleave', hideGhost); }); nodesLayer.appendChild(el);
  }); updateToolbars();
}
function nodeClick(e) { if (e.target.classList.contains('port')) return; e.stopPropagation(); const id = e.currentTarget.dataset.id; if (e.ctrlKey || e.metaKey || e.shiftKey) selectedIds.has(id) ? selectedIds.delete(id) : selectedIds.add(id); else selectOnly(id); state.selected = selectedIds.size === 1 ? [...selectedIds][0] : null; state.selectedEdge = null; renderAll(); }
function startNodeDrag(e) { if (e.button !== 0 || e.target.classList.contains('port') || e.target.isContentEditable) return; e.stopPropagation(); const id = e.currentTarget.dataset.id; if (!selectedIds.has(id)) selectOnly(id); snapshot(); const starts = selectedNodes().map(n => ({ n, x: n.x, y: n.y })); drag = { starts, startX: e.clientX, startY: e.clientY, moved: false }; e.currentTarget.setPointerCapture(e.pointerId); e.currentTarget.onpointermove = moveNode; e.currentTarget.onpointerup = endNodeDrag; renderNodes(); }
function moveNode(e) { if (!drag) return; drag.moved = true; drag.starts.forEach(item => { item.n.x = item.x + (e.clientX - drag.startX) / state.zoom; item.n.y = item.y + (e.clientY - drag.startY) / state.zoom; const el = document.querySelector(`[data-id="${item.n.id}"]`); el.style.left = item.n.x + 'px'; el.style.top = item.n.y + 'px'; }); renderEdges(); renderMinimap(); }
function nearestSide(node, clientX, clientY) { const rect = document.querySelector(`[data-id="${node.id}"]`).getBoundingClientRect(), distances = { left: Math.abs(clientX - rect.left), right: Math.abs(clientX - rect.right), top: Math.abs(clientY - rect.top), bottom: Math.abs(clientY - rect.bottom) }; return Object.entries(distances).sort((a,b) => a[1]-b[1])[0][0]; }
function sideVector(side) { return { top:{x:0,y:-1}, right:{x:1,y:0}, bottom:{x:0,y:1}, left:{x:-1,y:0} }[side]; }
function directionalCurve(a, b, fromSide='right', toSide='left') { const va=sideVector(fromSide), vb=sideVector(toSide), distance=Math.max(70,Math.hypot(b.x-a.x,b.y-a.y)*.42); return `M ${a.x} ${a.y} C ${a.x+va.x*distance} ${a.y+va.y*distance}, ${b.x+vb.x*distance} ${b.y+vb.y*distance}, ${b.x} ${b.y}`; }

function showGhost(e) { if(connectionDrag)return; const el=e.currentTarget.closest('.diagram-node'), node=state.nodes.find(n=>n.id===el.dataset.id), side=e.currentTarget.dataset.side, ghost=el.querySelector('.ghost-node'), offsets={top:[0,-190],right:[280,0],bottom:[0,190],left:[-280,0]}[side]; ghost.style.transform=`translate(${offsets[0]}px,${offsets[1]}px)`; ghost.classList.add('show'); const target={...node,x:node.x+offsets[0],y:node.y+offsets[1],type:'node',shape:'node'}, start=anchor(node,side), end=anchor(target,opposite(side)); $('connectionPreview').setAttribute('d',directionalCurve(start,end,side,opposite(side))); $('connectionPreview').classList.remove('hidden'); ghostConnection=true; }
function hideGhost(e) { e.currentTarget.closest('.diagram-node').querySelector('.ghost-node').classList.remove('show'); if(ghostConnection&&!connectionDrag){$('connectionPreview').classList.add('hidden');ghostConnection=null;} }
function moveConnection(e) { if(!connectionDrag)return; connectionDrag.moved=Math.hypot(e.clientX-connectionDrag.startX,e.clientY-connectionDrag.startY)>6; const rect=canvas.getBoundingClientRect(), end={x:(e.clientX-rect.left)/state.zoom,y:(e.clientY-rect.top)/state.zoom}; $('connectionPreview').setAttribute('d',directionalCurve(connectionDrag.start,end,connectionDrag.side,opposite(connectionDrag.side))); }
function endConnection(e) { if(!connectionDrag)return; const info=connectionDrag;connectionDrag=null;$('connectionPreview').classList.add('hidden');const targetEl=document.elementFromPoint(e.clientX,e.clientY)?.closest('.diagram-node');if(info.moved&&targetEl&&targetEl.dataset.id!==info.nodeId){const target=state.nodes.find(n=>n.id===targetEl.dataset.id);createEdge(info.nodeId,target.id,info.side,nearestSide(target,e.clientX,e.clientY));}else if(!info.moved)createDirectionalNode(info.nodeId,info.side); }
function createEdge(from,to,fromSide='right',toSide='left'){snapshot();state.edges.push({from,to,fromSide,toSide,label:'',shape:'curve',direction:'forward'});selectedIds.clear();state.selected=null;state.selectedEdge=state.edges.length-1;renderAll();markChanged();}
function updateToolbars(){const nodes=selectedNodes(),edge=state.edges[state.selectedEdge];$('selectionToolbar').classList.toggle('hidden',!nodes.length);$('edgeToolbar').classList.toggle('hidden',!edge);$('editNodeBtn').classList.toggle('hidden',nodes.length!==1);$('duplicateNodeBtn').classList.toggle('hidden',nodes.length!==1);if(nodes.length){const first=nodes[0];$('nodeColor').value=first.color||'#1687ff';$('nodeShape').value=nodeVisualType(first);$('nodeFontSize').value=first.fontSize||13;$('nodeAlign').value=first.align||'center';}if(edge){$('edgeShape').value=edge.shape||'curve';$('edgeLabel').value=edge.label||'';$('edgeDirection').value=edge.direction||'forward';}}
function applyNodes(update){const nodes=selectedNodes();if(!nodes.length)return;snapshot();nodes.forEach(n=>Object.assign(n,update));renderAll();markChanged();}
function deleteSelected(){if(!selectedIds.size)return;snapshot();state.nodes=state.nodes.filter(n=>!selectedIds.has(n.id));state.edges=state.edges.filter(e=>!selectedIds.has(e.from)&&!selectedIds.has(e.to));selectedIds.clear();state.selected=null;renderAll();markChanged();}
function generateCode(){let out='flowchart TD\n';state.nodes.forEach(n=>{const label=n.label.replace(/"/g,"'"),type=nodeVisualType(n);out+=type==='decision'?`  ${n.id}{"${label}"}\n`:type==='rounded'?`  ${n.id}("${label}")\n`:`  ${n.id}["${label}"]\n`;});state.edges.forEach((e,i)=>{out+=`  ${e.from} ${mermaidArrow(e)}${e.label?`|${e.label}|`:''} ${e.to}\n  %% flowcharts-edge:${i} shape=${e.shape||'curve'} fromSide=${e.fromSide||'right'} toSide=${e.toSide||'left'}\n`;});state.nodes.filter(n=>n.color).forEach(n=>out+=`  style ${n.id} fill:${n.color},stroke:${n.color},color:#ffffff\n`);return out.trim();}
function renderMinimap(){const content=$('minimapContent'),viewport=$('minimapViewport');content.innerHTML='';if(!state.nodes.length)return;const minX=Math.min(...state.nodes.map(n=>n.x))-100,minY=Math.min(...state.nodes.map(n=>n.y))-100,maxX=Math.max(...state.nodes.map(n=>n.x+180))+100,maxY=Math.max(...state.nodes.map(n=>n.y+120))+100,scale=Math.min(210/(maxX-minX),105/(maxY-minY));const map=p=>({x:5+(p.x-minX)*scale,y:8+(p.y-minY)*scale});state.edges.forEach(e=>{const a=state.nodes.find(n=>n.id===e.from),b=state.nodes.find(n=>n.id===e.to);if(!a||!b)return;const p=map({x:a.x+90,y:a.y+36}),q=map({x:b.x+90,y:b.y+36}),line=document.createElementNS('http://www.w3.org/2000/svg','line');for(const[k,v]of Object.entries({x1:p.x,y1:p.y,x2:q.x,y2:q.y,stroke:'#64748b'}))line.setAttribute(k,v);content.appendChild(line)});state.nodes.forEach(n=>{const p=map(n),r=document.createElementNS('http://www.w3.org/2000/svg','rect');for(const[k,v]of Object.entries({x:p.x,y:p.y,width:Math.max(5,180*scale),height:Math.max(3,72*scale),rx:2,fill:n.color||'#64748b'}))r.setAttribute(k,v);content.appendChild(r)});const viewX=(-state.pan.x/state.zoom),viewY=(-state.pan.y/state.zoom),p=map({x:viewX,y:viewY});viewport.setAttribute('x',p.x);viewport.setAttribute('y',p.y);viewport.setAttribute('width',Math.min(210,canvasWrap.clientWidth/state.zoom*scale));viewport.setAttribute('height',Math.min(105,canvasWrap.clientHeight/state.zoom*scale));}
function applyTransform(){canvas.style.transform=`translate(${state.pan.x}px,${state.pan.y}px) scale(${state.zoom})`;$('zoomLabel').textContent=Math.round(state.zoom*100)+'%';renderMinimap();}
function canvasPoint(clientX,clientY){const rect=canvas.getBoundingClientRect();return{x:(clientX-rect.left)/state.zoom,y:(clientY-rect.top)/state.zoom};}
function startMarquee(e){if(e.button!==0||e.target!==canvas&&e.target!==nodesLayer)return;const p=canvasPoint(e.clientX,e.clientY);marqueeDrag={start:p,current:p};selectedIds.clear();state.selected=null;state.selectedEdge=null;$('marquee').classList.remove('hidden');updateMarquee();}
function updateMarquee(){if(!marqueeDrag)return;const a=marqueeDrag.start,b=marqueeDrag.current,left=Math.min(a.x,b.x),top=Math.min(a.y,b.y),right=Math.max(a.x,b.x),bottom=Math.max(a.y,b.y),el=$('marquee');Object.assign(el.style,{left:left+'px',top:top+'px',width:(right-left)+'px',height:(bottom-top)+'px'});selectedIds=new Set(state.nodes.filter(n=>{const s=nodeSize(n);return n.x>=left&&n.y>=top&&n.x+s.w<=right&&n.y+s.h<=bottom;}).map(n=>n.id));state.nodes.forEach(n=>document.querySelector(`[data-id="${n.id}"]`)?.classList.toggle('selected',selectedIds.has(n.id)));updateToolbars();}
function endMarquee(){if(!marqueeDrag)return;marqueeDrag=null;$('marquee').classList.add('hidden');state.selected=selectedIds.size===1?[...selectedIds][0]:null;renderAll();}
function beginSpaceCreate(){if(spaceCreate||selectedIds.size!==1)return;const from=state.nodes.find(n=>selectedIds.has(n.id));spaceCreate={from,side:'right',point:anchor(from,'right')};$('connectionPreview').classList.remove('hidden');}
function updateSpaceCreate(e){if(!spaceCreate)return;const p=canvasPoint(e.clientX,e.clientY),from=spaceCreate.from,dx=p.x-(from.x+90),dy=p.y-(from.y+36);spaceCreate.side=Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'bottom':'top');spaceCreate.point=p;$('connectionPreview').setAttribute('d',directionalCurve(anchor(from,spaceCreate.side),p,spaceCreate.side,opposite(spaceCreate.side)));}
function finishSpaceCreate(){if(!spaceCreate)return;const {from,side,point}=spaceCreate;spaceCreate=null;$('connectionPreview').classList.add('hidden');snapshot();const id=safeId('Nuevo proceso'),node={id,label:'Nuevo proceso',x:point.x-90,y:point.y-36,type:'node',color:null,fontSize:13,align:'center'};state.nodes.push(node);state.edges.push({from:from.id,to:id,fromSide:side,toSide:opposite(side),label:'',shape:'curve',direction:'forward'});selectOnly(id);renderAll();markChanged();setTimeout(()=>beginInlineEdit(id),50);}
canvas.addEventListener('pointerdown',startMarquee);
canvas.addEventListener('pointermove',e=>{if(marqueeDrag){marqueeDrag.current=canvasPoint(e.clientX,e.clientY);updateMarquee();}updateSpaceCreate(e)});
canvas.addEventListener('pointerup',endMarquee);
document.querySelectorAll('.color-presets button').forEach(button=>button.onclick=()=>applyNodes({color:button.dataset.color||null}));
$('nodeColor').oninput=e=>applyNodes({color:e.target.value});
$('nodeShape').onchange=e=>applyNodes({shape:e.target.value,type:e.target.value==='decision'?'decision':'node'});
$('nodeFontSize').onchange=e=>applyNodes({fontSize:Number(e.target.value)});
$('nodeAlign').onchange=e=>applyNodes({align:e.target.value});
$('themeBtn').onclick=()=>{const light=document.body.classList.toggle('light-theme');$('themeBtn').textContent=light?'◐ Tema oscuro':'☀ Tema claro';localStorage.setItem('flowcharts-theme',light?'light':'dark');};
if(localStorage.getItem('flowcharts-theme')==='light')$('themeBtn').click();
$('collapseCodeBtn').onclick=()=>{const panel=document.querySelector('.code-panel'),collapsed=panel.classList.toggle('collapsed');editorView.classList.toggle('code-collapsed',collapsed);$('collapseCodeBtn').textContent=collapsed?'‹':'›';setTimeout(()=>{applyTransform();},260);};
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&!document.activeElement.isContentEditable&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();beginSpaceCreate();}});
document.addEventListener('keyup',e=>{if(e.code==='Space'&&spaceCreate){e.preventDefault();finishSpaceCreate();}});
function createDirectionalNode(fromId,side){const from=state.nodes.find(n=>n.id===fromId),offset={top:[0,-190],right:[280,0],bottom:[0,190],left:[-280,0]}[side];snapshot();const id=safeId('Nuevo proceso'),node={id,label:'Nuevo proceso',x:from.x+offset[0],y:from.y+offset[1],type:'node',color:null,fontSize:13,align:'center'};state.nodes.push(node);state.edges.push({from:fromId,to:id,fromSide:side,toSide:opposite(side),label:'',shape:'curve',direction:'forward'});selectOnly(id);renderAll();markChanged();setTimeout(()=>beginInlineEdit(id),50);}
function addNode(type,x=450,y=300){snapshot();const label=type==='decision'?'Nueva decisión':'Nuevo proceso',id=safeId(label);state.nodes.push({id,label,x,y,type,color:null,fontSize:13,align:'center'});selectOnly(id);renderAll();markChanged();setTimeout(()=>beginInlineEdit(id),50);}
let suppressCanvasClick=false;
canvas.addEventListener('pointerdown',e=>{if(e.button===0&&(e.target===canvas||e.target===nodesLayer))suppressCanvasClick=false;},true);
canvas.addEventListener('pointermove',e=>{if(marqueeDrag&&Math.hypot(marqueeDrag.current.x-marqueeDrag.start.x,marqueeDrag.current.y-marqueeDrag.start.y)>5)suppressCanvasClick=true;},true);
canvas.addEventListener('click',e=>{if(suppressCanvasClick){e.stopImmediatePropagation();suppressCanvasClick=false;}},true);
canvas.addEventListener('click',e=>{if((e.target===canvas||e.target===nodesLayer)&&!suppressCanvasClick){selectedIds.clear();state.selected=null;state.selectedEdge=null;renderAll();}});

// Interaction reliability and multi-edge selection
let selectedEdges = new Set();
function startNodeDrag(e) {
  if (e.button !== 0 || e.target.classList.contains('port') || e.target.isContentEditable) return;
  e.stopPropagation();
  const id = e.currentTarget.dataset.id;
  if (!selectedIds.has(id)) selectOnly(id);
  selectedEdges.clear(); state.selectedEdge = null; snapshot();
  drag = { starts: selectedNodes().map(n => ({ n, x: n.x, y: n.y })), startX: e.clientX, startY: e.clientY, moved: false };
  e.currentTarget.setPointerCapture(e.pointerId);
  e.currentTarget.onpointermove = moveNode;
  e.currentTarget.onpointerup = endNodeDrag;
  document.querySelectorAll('.diagram-node').forEach(el => el.classList.toggle('selected', selectedIds.has(el.dataset.id)));
  updateToolbars();
}

function deleteCurrentSelection(){if(selectedIds.size)return deleteSelected();if(selectedEdges.size){snapshot();state.edges=state.edges.filter((_,i)=>!selectedEdges.has(i));selectedEdges.clear();state.selectedEdge=null;renderAll();markChanged();}}
function updateToolbars(){const nodes=selectedNodes(),edge=state.edges[state.selectedEdge];$('selectionToolbar').classList.toggle('hidden',!nodes.length);$('edgeToolbar').classList.toggle('hidden',!selectedEdges.size);$('editNodeBtn').classList.toggle('hidden',nodes.length!==1);$('duplicateNodeBtn').classList.toggle('hidden',nodes.length!==1);if(nodes.length){const first=nodes[0];$('nodeColor').value=first.color||'#1687ff';$('nodeShape').value=nodeVisualType(first);$('nodeFontSize').value=first.fontSize||13;$('nodeAlign').value=first.align||'center'}if(edge){$('edgeShape').value=edge.shape||'curve';$('edgeLabel').value=edge.label||'';$('edgeDirection').value=edge.direction||'forward'}}
function updateSelectedEdge(){if(!selectedEdges.size)return;snapshot();selectedEdges.forEach(i=>{const e=state.edges[i];if(e){e.shape=$('edgeShape').value;e.direction=$('edgeDirection').value;e.label=$('edgeLabel').value}});renderEdges();updateCode();markChanged()}
function updateSpaceCreate(e){if(!spaceCreate)return;const p=canvasPoint(e.clientX,e.clientY),from=spaceCreate.from,targetEl=document.elementFromPoint(e.clientX,e.clientY)?.closest('.diagram-node'),target=targetEl&&targetEl.dataset.id!==from.id?state.nodes.find(n=>n.id===targetEl.dataset.id):null,dx=p.x-(from.x+90),dy=p.y-(from.y+36);spaceCreate.side=Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'bottom':'top');spaceCreate.point=p;spaceCreate.target=target;spaceCreate.targetSide=target?nearestSide(target,e.clientX,e.clientY):null;document.querySelectorAll('.diagram-node.space-target').forEach(el=>el.classList.remove('space-target'));if(target)targetEl.classList.add('space-target');const end=target?anchor(target,spaceCreate.targetSide):p;$('connectionPreview').setAttribute('d',directionalCurve(anchor(from,spaceCreate.side),end,spaceCreate.side,target?spaceCreate.targetSide:opposite(spaceCreate.side)))}
function finishSpaceCreate(){if(!spaceCreate)return;const {from,side,point,target,targetSide}=spaceCreate;spaceCreate=null;$('connectionPreview').classList.add('hidden');document.querySelectorAll('.diagram-node.space-target').forEach(el=>el.classList.remove('space-target'));if(target){createEdge(from.id,target.id,side,targetSide);return}snapshot();const id=safeId('Nuevo proceso'),node={id,label:'Nuevo proceso',x:point.x-90,y:point.y-36,type:'node',color:null,fontSize:13,align:'center'};state.nodes.push(node);state.edges.push({from:from.id,to:id,fromSide:side,toSide:opposite(side),label:'',shape:'curve',direction:'forward'});selectOnly(id);renderAll();markChanged();setTimeout(()=>beginInlineEdit(id),50)}
function hideCodePanel(){document.querySelector('.code-panel').classList.add('fully-hidden');editorView.classList.add('code-hidden');$('showCodeBtn').classList.remove('hidden');setTimeout(applyTransform,50)}
function showCodePanel(){document.querySelector('.code-panel').classList.remove('fully-hidden','collapsed');editorView.classList.remove('code-hidden','code-collapsed');$('showCodeBtn').classList.add('hidden');setTimeout(applyTransform,50)}
$('collapseCodeBtn').onclick=hideCodePanel;$('showCodeBtn').onclick=showCodePanel;
$('deleteEdgeBtn').onclick=deleteCurrentSelection;$('deleteNodeBtn').onclick=deleteCurrentSelection;
document.addEventListener('keydown',e=>{if((e.key==='Delete'||e.key==='Del')&&!document.activeElement.isContentEditable&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();e.stopImmediatePropagation();deleteCurrentSelection()}},true);
function nodeClick(e){if(e.target.classList.contains('port'))return;e.stopPropagation();const id=e.currentTarget.dataset.id;selectedEdges.clear();if(e.ctrlKey||e.metaKey||e.shiftKey)selectedIds.has(id)?selectedIds.delete(id):selectedIds.add(id);else selectOnly(id);state.selected=selectedIds.size===1?[...selectedIds][0]:null;state.selectedEdge=null;renderAll()}
function createEdge(from,to,fromSide='right',toSide='left'){snapshot();state.edges.push({from,to,fromSide,toSide,label:'',shape:'curve',direction:'forward'});selectedIds.clear();selectedEdges=new Set([state.edges.length-1]);state.selected=null;state.selectedEdge=state.edges.length-1;renderAll();markChanged()}
canvas.addEventListener('click',e=>{if(e.target===canvas||e.target===nodesLayer){selectedEdges.clear();state.selectedEdge=null;}},true);
function deleteSelected(){if(!selectedIds.size)return;snapshot();state.nodes=state.nodes.filter(n=>!selectedIds.has(n.id));state.edges=state.edges.filter(e=>!selectedIds.has(e.from)&&!selectedIds.has(e.to));selectedIds.clear();selectedEdges.clear();state.selected=null;state.selectedEdge=null;renderAll();markChanged()}

// Rich edge editing, title nodes, and reliable selection surface
function nodeVisualType(n){return n.shape||n.type||'node'}
function nodeSize(n){const type=nodeVisualType(n);return type==='decision'?{w:120,h:120}:type==='title'?{w:200,h:60}:{w:180,h:72}}
function renderNodes(){nodesLayer.innerHTML='';state.nodes.forEach(n=>{const type=nodeVisualType(n),el=document.createElement('div');el.className=`diagram-node ${type==='decision'?'decision':''} ${type==='rounded'?'rounded':''} ${type==='title'?'title-node':''} ${selectedIds.has(n.id)?'selected':''} ${n.color?'colored':''}`;el.dataset.id=n.id;el.style.left=n.x+'px';el.style.top=n.y+'px';el.style.setProperty('--node-color',n.color||'#1687ff');el.style.setProperty('--node-font-size',(n.fontSize||13)+'px');el.style.setProperty('--node-align',n.align||'center');el.innerHTML=`<span class="node-kind">${type==='title'?'TÍTULO':type==='decision'?'DECISIÓN':''}</span><span class="node-label"></span>${['top','right','bottom','left'].map(p=>`<button class="port ${p}" data-side="${p}" aria-label="Conectar hacia ${p}"></button>`).join('')}<span class="ghost-node"></span>`;el.querySelector('.node-label').textContent=n.label;el.addEventListener('pointerdown',startNodeDrag);el.addEventListener('click',nodeClick);el.addEventListener('dblclick',e=>{if(!e.target.classList.contains('port')){e.stopPropagation();beginInlineEdit(n.id)}});el.querySelectorAll('.port').forEach(port=>{port.addEventListener('pointerdown',startConnection);port.addEventListener('mouseenter',showGhost);port.addEventListener('mouseleave',hideGhost)});nodesLayer.appendChild(el)});updateToolbars()}
function nodeClick(e){if(e.target.classList.contains('port'))return;e.stopPropagation();const id=e.currentTarget.dataset.id,multi=e.ctrlKey||e.metaKey;if(multi)selectedIds.has(id)?selectedIds.delete(id):selectedIds.add(id);else{selectOnly(id);selectedEdges.clear()}state.selected=selectedIds.size===1?[...selectedIds][0]:null;state.selectedEdge=selectedEdges.size?[...selectedEdges][0]:null;renderAll()}
function pointBetween(a,b,t){return{x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t}}







function mermaidArrow(edge){if(edge.dashed)return edge.direction==='both'?'<-.->':edge.direction==='back'?'<-.-':'-.->';return edge.direction==='both'?'<-->':edge.direction==='back'?'<--':'-->'}
function updateToolbars(){const nodes=selectedNodes(),edge=state.edges[state.selectedEdge];$('selectionToolbar').classList.toggle('hidden',!nodes.length);$('edgeToolbar').classList.toggle('hidden',!selectedEdges.size);$('editNodeBtn').classList.toggle('hidden',nodes.length!==1);$('duplicateNodeBtn').classList.toggle('hidden',nodes.length!==1);if(nodes.length){const first=nodes[0];$('nodeColor').value=first.color||'#1687ff';$('nodeShape').value=nodeVisualType(first)==='title'?'node':nodeVisualType(first);$('nodeFontSize').value=first.fontSize||13;$('nodeAlign').value=first.align||'center'}if(edge){$('edgeShape').value=edge.shape||'curve';$('edgeDashed').checked=!!edge.dashed;$('edgeLabel').value=edge.label||'';$('edgeLabelPos').value=edge.labelPos??50}}
function updateSelectedEdge(){if(!selectedEdges.size)return;snapshot();selectedEdges.forEach(i=>{const e=state.edges[i];if(e){e.shape=$('edgeShape').value;e.dashed=$('edgeDashed').checked;e.label=$('edgeLabel').value;e.labelPos=Number($('edgeLabelPos').value);if(e.shape==='straight'){delete e.control;delete e.bendX}}});renderEdges();updateCode();markChanged()}
$('edgeShape').onchange=updateSelectedEdge;$('edgeDashed').onchange=updateSelectedEdge;$('edgeLabel').oninput=updateSelectedEdge;$('edgeLabelPos').oninput=updateSelectedEdge;
$('reverseEdgeBtn').onclick=()=>{if(!selectedEdges.size)return;snapshot();selectedEdges.forEach(i=>{const e=state.edges[i];if(!e)return;[e.from,e.to]=[e.to,e.from];[e.fromSide,e.toSide]=[e.toSide,e.fromSide];if(e.direction==='back')e.direction='forward'});renderAll();markChanged()};
function addNode(type,x=450,y=300){snapshot();const isTitle=type==='title',label=isTitle?'Nuevo título':type==='decision'?'Nueva decisión':'Nuevo proceso',id=safeId(label);state.nodes.push({id,label,x,y,type,color:null,fontSize:isTitle?20:13,align:'center'});selectOnly(id);renderAll();markChanged();setTimeout(()=>beginInlineEdit(id),50)}
document.querySelectorAll('.tool[data-tool]').forEach(b=>b.onclick=()=>{const type=b.dataset.tool;if(['node','decision','title'].includes(type))addNode(type)});
// Ctrl+Z / Ctrl+Shift+Z
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.stopImmediatePropagation();(e.shiftKey?$('redoBtn'):$('undoBtn')).click()}},true);
// Marquee uses viewport coordinates so it can grow equally in every direction.
function startViewportMarquee(e){if(e.button!==0||![canvasWrap,canvas,nodesLayer].includes(e.target))return;e.stopImmediatePropagation();const rect=canvasWrap.getBoundingClientRect();marqueeDrag={startClient:{x:e.clientX,y:e.clientY},start:canvasPoint(e.clientX,e.clientY),current:canvasPoint(e.clientX,e.clientY)};if(!e.ctrlKey&&!e.metaKey){selectedIds.clear();selectedEdges.clear()}canvasWrap.appendChild($('marquee'));$('marquee').classList.remove('hidden');canvasWrap.setPointerCapture(e.pointerId);updateViewportMarquee(e)}
function updateViewportMarquee(e){if(!marqueeDrag)return;e.stopImmediatePropagation();const rect=canvasWrap.getBoundingClientRect(),x1=marqueeDrag.startClient.x-rect.left,y1=marqueeDrag.startClient.y-rect.top,x2=e.clientX-rect.left,y2=e.clientY-rect.top,left=Math.min(x1,x2),top=Math.min(y1,y2),right=Math.max(x1,x2),bottom=Math.max(y1,y2),el=$('marquee');Object.assign(el.style,{left:left+'px',top:top+'px',width:(right-left)+'px',height:(bottom-top)+'px'});const worldA=canvasPoint(rect.left+left,rect.top+top),worldB=canvasPoint(rect.left+right,rect.top+bottom);state.nodes.forEach(n=>{const size=nodeSize(n),inside=n.x>=worldA.x&&n.y>=worldA.y&&n.x+size.w<=worldB.x&&n.y+size.h<=worldB.y;if(inside)selectedIds.add(n.id)});renderNodes()}
function endViewportMarquee(e){if(!marqueeDrag)return;e.stopImmediatePropagation();marqueeDrag=null;$('marquee').classList.add('hidden');state.selected=selectedIds.size===1?[...selectedIds][0]:null;renderAll()}
canvasWrap.addEventListener('pointerdown',startViewportMarquee,true);canvasWrap.addEventListener('pointermove',updateViewportMarquee,true);canvasWrap.addEventListener('pointerup',endViewportMarquee,true);
// Hand cursors for canvas and nodes.
canvasWrap.addEventListener('pointerdown',e=>{if(e.button===2)canvasWrap.classList.add('panning')},true);canvasWrap.addEventListener('pointerup',()=>canvasWrap.classList.remove('panning'),true);canvasWrap.addEventListener('pointercancel',()=>canvasWrap.classList.remove('panning'),true);
function generateCode(){let out='flowchart TD\n';state.nodes.forEach(n=>{const label=n.label.replace(/"/g,"'"),type=nodeVisualType(n);out+=type==='decision'?`  ${n.id}{"${label}"}\n`:type==='rounded'?`  ${n.id}("${label}")\n`:`  ${n.id}["${label}"]\n`});state.edges.forEach((e,i)=>{out+=`  ${e.from} ${mermaidArrow(e)}${e.label?`|${e.label}|`:''} ${e.to}\n  %% flowcharts-edge:${i} shape=${e.shape||'curve'} dashed=${!!e.dashed} fromSide=${e.fromSide||'right'} toSide=${e.toSide||'left'} labelPos=${e.labelPos??50}\n`});state.nodes.filter(n=>n.color||nodeVisualType(n)==='title').forEach(n=>{if(nodeVisualType(n)==='title')out+=`  style ${n.id} fill:none,stroke:none,color:${n.color||'#dbe7f5'}\n`;else out+=`  style ${n.id} fill:${n.color},stroke:${n.color},color:#ffffff\n`});return out.trim()}
function renderMinimap(){const content=$('minimapContent'),viewport=$('minimapViewport');content.innerHTML='';if(!state.nodes.length)return;const minX=Math.min(...state.nodes.map(n=>n.x)),minY=Math.min(...state.nodes.map(n=>n.y)),maxX=Math.max(...state.nodes.map(n=>n.x+nodeSize(n).w)),maxY=Math.max(...state.nodes.map(n=>n.y+nodeSize(n).h)),spanX=Math.max(1,maxX-minX),spanY=Math.max(1,maxY-minY),scale=Math.min(190/spanX,90/spanY),offsetX=(220-spanX*scale)/2,offsetY=(112-spanY*scale)/2+4,map=p=>({x:offsetX+(p.x-minX)*scale,y:offsetY+(p.y-minY)*scale});state.edges.forEach(e=>{const a=state.nodes.find(n=>n.id===e.from),b=state.nodes.find(n=>n.id===e.to);if(!a||!b)return;const sa=nodeSize(a),sb=nodeSize(b),p=map({x:a.x+sa.w/2,y:a.y+sa.h/2}),q=map({x:b.x+sb.w/2,y:b.y+sb.h/2}),line=document.createElementNS('http://www.w3.org/2000/svg','line');for(const[k,v]of Object.entries({x1:p.x,y1:p.y,x2:q.x,y2:q.y,stroke:'#64748b'}))line.setAttribute(k,v);content.appendChild(line)});state.nodes.forEach(n=>{const p=map(n),size=nodeSize(n),r=document.createElementNS('http://www.w3.org/2000/svg','rect');for(const[k,v]of Object.entries({x:p.x,y:p.y,width:Math.max(4,size.w*scale),height:Math.max(3,size.h*scale),rx:2,fill:n.color||'#64748b'}))r.setAttribute(k,v);content.appendChild(r)});const view=map({x:-state.pan.x/state.zoom,y:-state.pan.y/state.zoom});viewport.setAttribute('x',view.x);viewport.setAttribute('y',view.y);viewport.setAttribute('width',canvasWrap.clientWidth/state.zoom*scale);viewport.setAttribute('height',canvasWrap.clientHeight/state.zoom*scale)}
function endNodeDrag(){document.querySelectorAll('.diagram-node.dragging').forEach(el=>el.classList.remove('dragging'));if(drag?.moved)markChanged();drag=null}
document.addEventListener('pointerdown',e=>{const node=e.target.closest?.('.diagram-node');if(node&&e.button===0&&!e.target.classList.contains('port'))node.classList.add('dragging')},true);

// Final interaction hardening, smart edge routes, and responsive minimap
let isDirty=false,minimapTimer=null;
function markChanged(){isDirty=true;$('saveState').textContent='Cambios sin guardar';updateCode()}
function markSaved(){isDirty=false;$('saveState').textContent='Cambios guardados localmente'}
document.addEventListener('dragstart',e=>e.preventDefault());
document.addEventListener('selectstart',e=>{if(!e.target.isContentEditable&&!['INPUT','TEXTAREA'].includes(e.target.tagName))e.preventDefault()});
function showMinimap(){const el=$('minimap');el.classList.add('visible');clearTimeout(minimapTimer);minimapTimer=setTimeout(()=>el.classList.remove('visible'),2200)}
$('minimap').addEventListener('mouseenter',()=>{clearTimeout(minimapTimer);$('minimap').classList.add('visible')});$('minimap').addEventListener('mouseleave',showMinimap);
const originalApplyTransform=applyTransform;applyTransform=function(){originalApplyTransform();showMinimap()};
const controls=$('minimapControls'),headerControls=document.querySelector('.header-center');if(controls&&headerControls)controls.appendChild(headerControls);
$('homeThemeBtn').onclick=()=>$('themeBtn').click();
const syncThemeLabels=()=>{const light=document.body.classList.contains('light-theme');$('homeThemeBtn').querySelector('b').textContent=light?'Oscuro':'Claro'};$('themeBtn').addEventListener('click',syncThemeLabels);syncThemeLabels();






function pathPoint(path,percent){const length=path.getTotalLength();return path.getPointAtLength(length*Math.max(0,Math.min(1,percent)))}




async function addRecent(handle,name){if(!handle)return;const items=await getRecents();let existing=null;for(const item of items){try{if(await item.handle.isSameEntry(handle)){existing=item;break}}catch{}}const store=await recentStore('readwrite');if(existing)await new Promise(resolve=>{const r=store.delete(existing.id);r.onsuccess=resolve});const item={id:`${handle.name}:${Date.now()}`,name:name||handle.name,handle,updated:Date.now()};await new Promise((resolve,reject)=>{const r=store.put(item);r.onsuccess=resolve;r.onerror=()=>reject(r.error)});renderRecent()}

// Polished UX: smooth movement, independent controls, and in-app leave confirmation
const floatingControls=document.querySelector('.header-center');
if(floatingControls){floatingControls.classList.add('floating-board-controls');canvasWrap.appendChild(floatingControls)}
function moveNode(e){if(!drag)return;drag.moved=true;drag.starts.forEach(item=>{item.n.x=item.x+(e.clientX-drag.startX)/state.zoom;item.n.y=item.y+(e.clientY-drag.startY)/state.zoom;const el=document.querySelector(`[data-id="${item.n.id}"]`);el.style.left=item.n.x+'px';el.style.top=item.n.y+'px'});renderEdges();renderMinimap()}
function renderNodes(){nodesLayer.innerHTML='';state.nodes.forEach(n=>{const type=nodeVisualType(n),el=document.createElement('div');el.className=`diagram-node ${type==='decision'?'decision':''} ${type==='rounded'?'rounded':''} ${type==='title'?'title-node':''} ${selectedIds.has(n.id)?'selected':''} ${n.color?'colored':''}`;el.dataset.id=n.id;el.style.left=n.x+'px';el.style.top=n.y+'px';el.style.setProperty('--node-color',n.color||'#1687ff');el.style.setProperty('--node-font-size',(n.fontSize||13)+'px');el.style.setProperty('--node-align',n.align||'center');el.innerHTML=`<span class="node-label"></span>${['top','right','bottom','left'].map(p=>`<button class="port ${p}" data-side="${p}" aria-label="Conectar hacia ${p}"></button>`).join('')}<span class="ghost-node"></span>`;el.querySelector('.node-label').textContent=n.label;el.addEventListener('pointerdown',startNodeDrag);el.addEventListener('click',nodeClick);el.addEventListener('dblclick',e=>{if(!e.target.classList.contains('port')){e.stopPropagation();beginInlineEdit(n.id)}});el.querySelectorAll('.port').forEach(port=>{port.addEventListener('pointerdown',startConnection);port.addEventListener('mouseenter',showGhost);port.addEventListener('mouseleave',hideGhost)});nodesLayer.appendChild(el)});updateToolbars()}
function exitToHome(){isDirty=false;editorView.classList.add('hidden');homeView.classList.remove('hidden');renderRecent()}
$('backBtn').onclick=()=>{if(isDirty)$('leaveDialog').showModal();else exitToHome()};
$('stayBtn').onclick=()=>$('leaveDialog').close();
$('leaveBtn').onclick=()=>{$('leaveDialog').close();exitToHome()};
// The app uses its own leave dialog for in-app navigation.
window.onbeforeunload=null;

// Standards-oriented Mermaid parser and direct connection routing
function parseCode(code){
  const parsed=FlowchartsParser.parse(code);if(!parsed.nodes.length)return;
  snapshot();selectedIds.clear();selectedEdges.clear();state.nodes=parsed.nodes;state.edges=parsed.edges;state.groups=parsed.groups;
  logicalLayout(state.nodes,state.edges);renderAll();markChanged();fitView();
}

function generateCode(){
  let out='flowchart TD\n',grouped=new Set();const definition=n=>{const label=n.label.replace(/"/g,"'"),type=nodeVisualType(n);return type==='decision'?`    ${n.id}{"${label}"}\n`:type==='rounded'?`    ${n.id}("${label}")\n`:`    ${n.id}["${label}"]\n`};
  (state.groups||[]).forEach(group=>{const members=state.nodes.filter(n=>n.group===group.id);if(!members.length)return;out+=`  subgraph ${group.id} ["${group.label.replace(/"/g,"'")}"]\n`;members.forEach(n=>{out+=definition(n);grouped.add(n.id)});out+='  end\n'});
  state.nodes.filter(n=>!grouped.has(n.id)).forEach(n=>out+=definition(n));
  state.edges.forEach((e,i)=>{out+=`  ${e.from} ${e.label?`-- "${e.label.replace(/"/g,"'")}" -->` : mermaidArrow(e)} ${e.to}\n  %% flowcharts-edge:${i} shape=${e.shape||'curve'} dashed=${!!e.dashed} fromSide=${e.fromSide||'right'} toSide=${e.toSide||'left'} labelPos=${e.labelPos??50}\n`});
  state.nodes.filter(n=>n.color).forEach(n=>out+=`  style ${n.id} fill:${n.color},stroke:${n.color},color:#ffffff\n`);return out.trim();
}
function normalizeData(data){return{nodes:(data.nodes||[]).map(node=>({color:null,fontSize:13,align:'center',...node})),edges:(data.edges||[]).map(edge=>({label:'',shape:'curve',direction:'forward',...edge})),groups:data.groups||[]}}

// Group-aware automatic layout and direct edge manipulation
const groupsLayer=$('groupsLayer');
let toolbarTimer=null;
function layoutGraph(nodes,edges,originX,originY){
  if(!nodes.length)return{x:originX,y:originY,w:0,h:0};
  const ids=new Set(nodes.map(n=>n.id)),incoming=new Map(nodes.map(n=>[n.id,0])),outgoing=new Map(nodes.map(n=>[n.id,[]]));
  edges.forEach(e=>{if(ids.has(e.from)&&ids.has(e.to)){incoming.set(e.to,incoming.get(e.to)+1);outgoing.get(e.from).push(e.to)}});
  const roots=nodes.filter(n=>!incoming.get(n.id)).map(n=>n.id),queue=(roots.length?roots:[nodes[0].id]).map(id=>[id,0]),levels=new Map();
  while(queue.length){const[id,level]=queue.shift();if(levels.has(id))continue;levels.set(id,level);outgoing.get(id)?.forEach(next=>{if(!levels.has(next))queue.push([next,level+1])})}
  nodes.forEach(n=>{if(!levels.has(n.id))levels.set(n.id,Math.max(0,...levels.values())+1)});
  const columns={};nodes.forEach(n=>(columns[levels.get(n.id)]||=[]).push(n));
  const xGap=260,yGap=125,maxRows=Math.max(...Object.values(columns).map(column=>column.length));
  Object.entries(columns).forEach(([level,column])=>{const columnHeight=(column.length-1)*yGap;column.forEach((node,row)=>{node.x=originX+Number(level)*xGap;node.y=originY+(maxRows-1)*yGap/2-columnHeight/2+row*yGap})});
  return{x:originX-55,y:originY-65,w:(Math.max(...levels.values())+1)*xGap+35,h:Math.max(150,maxRows*yGap+20)};
}
function logicalLayout(nodes,edges){
  const groups=state.groups||[],groupBounds=[];let cursorX=220;
  groups.forEach(group=>{const members=nodes.filter(n=>n.group===group.id),memberIds=new Set(members.map(n=>n.id)),internal=edges.filter(e=>memberIds.has(e.from)&&memberIds.has(e.to));const bounds=layoutGraph(members,internal,cursorX,220);group.bounds=bounds;groupBounds.push(bounds);cursorX+=bounds.w+170});
  const grouped=new Set(groups.flatMap(g=>nodes.filter(n=>n.group===g.id).map(n=>n.id))),loose=nodes.filter(n=>!grouped.has(n.id));if(loose.length)layoutGraph(loose,edges.filter(e=>!grouped.has(e.from)&&!grouped.has(e.to)),220,Math.max(220,...groupBounds.map(b=>b.y+b.h+170)));
}
function renderGroups(){groupsLayer.innerHTML='';(state.groups||[]).forEach(group=>{const members=state.nodes.filter(n=>n.group===group.id);if(!members.length)return;const minX=Math.min(...members.map(n=>n.x))-65,minY=Math.min(...members.map(n=>n.y))-75,maxX=Math.max(...members.map(n=>n.x+nodeSize(n).w))+65,maxY=Math.max(...members.map(n=>n.y+nodeSize(n).h))+65,el=document.createElement('section');el.className='flow-group';el.style.left=minX+'px';el.style.top=minY+'px';el.style.width=(maxX-minX)+'px';el.style.height=(maxY-minY)+'px';el.innerHTML='<strong></strong>';el.querySelector('strong').textContent=group.label;groupsLayer.appendChild(el)})}
function renderAll(){renderGroups();renderNodes();renderEdges();updateCode();renderMinimap();updateToolbars()}
function hideContextDuringNavigation(){document.body.classList.add('board-navigating');clearTimeout(toolbarTimer);toolbarTimer=setTimeout(()=>document.body.classList.remove('board-navigating'),450)}
const navigationApplyTransform=applyTransform;applyTransform=function(){hideContextDuringNavigation();navigationApplyTransform()};
canvasWrap.addEventListener('pointermove',()=>{if(panDrag)hideContextDuringNavigation()});


// Connections follow nodes and selected shape; there are no manual shaping controls.


function logicalLayout(nodes,edges){const result=FlowchartsLayout.layout(nodes,edges,state.groups||[]);canvas.style.width=Math.max(2400,result.width||0)+'px';canvas.style.height=Math.max(1600,result.height||0)+'px';return result}

function edgePath(edge,a,b){const p1=anchor(a,edge.fromSide||'right'),p2=anchor(b,edge.toSide||'left');if(edge.shape==='straight')return`M ${p1.x} ${p1.y} L ${p2.x} ${p2.y}`;if(edge.shape==='corner'){const middle=(p1.x+p2.x)/2;return`M ${p1.x} ${p1.y} L ${middle} ${p1.y} L ${middle} ${p2.y} L ${p2.x} ${p2.y}`}return directionalCurve(p1,p2,edge.fromSide||'right',edge.toSide||'left')}
function renderEdges(){edgesGroup.innerHTML='';state.edges.forEach((edge,index)=>{const a=state.nodes.find(node=>node.id===edge.from),b=state.nodes.find(node=>node.id===edge.to);if(!a||!b)return;const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',edgePath(edge,a,b));path.setAttribute('class',`edge ${edge.dashed?'dashed':''} ${selectedEdges.has(index)?'selected':''}`);if(edge.direction!=='back')path.setAttribute('marker-end','url(#arrow)');if(edge.direction==='back'||edge.direction==='both')path.setAttribute('marker-start','url(#arrow-start)');path.addEventListener('pointerdown',event=>{event.stopPropagation();const multi=event.ctrlKey||event.metaKey;if(multi)selectedEdges.has(index)?selectedEdges.delete(index):selectedEdges.add(index);else{selectedEdges=new Set([index]);selectedIds.clear()}state.selected=selectedIds.size===1?[...selectedIds][0]:null;state.selectedEdge=selectedEdges.size?[...selectedEdges][0]:null;renderAll()});edgesGroup.appendChild(path);const labelPoint=pathPoint(path,(edge.labelPos??50)/100);if(edge.label){const text=document.createElementNS('http://www.w3.org/2000/svg','text');text.setAttribute('x',labelPoint.x);text.setAttribute('y',labelPoint.y-10);text.setAttribute('class','edge-text');text.textContent=edge.label;edgesGroup.appendChild(text)}})}
